config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get '/home/about' => "homes#about", as: 'about'
  devise_for :users

  resources :books, only: [:new, :create, :update, :index, :show, :edit, :destroy]
  resources :users, only: [:new, :index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, length: { in: 1..200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :profile_image

         has_many :books, dependent: :destroy

  validates :name, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!, only: [:index, :show, :edit]
    before_action :current_user, only: [:edit, :update]

    def after_sign_in_path_for(resource)
     user_path(resource)
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only:[:edit]

  def new
    @book = Book.new
    link_to book_path(@book)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @current_user = current_user
    @user = User.find_by(params[:id])
  end

  def show
    @new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user
  end

  def destroy
    book = Book.find(params[:id])
      if book.user.id == current_user.id
        book.destroy
        redirect_to "/books"
      end
  end



  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
  unless @book.user == current_user
     redirect_to books_path
  end

  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only:[:edit]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome! You have signed up successfully."
      redirect_to user_path
    else
      render signup
    end
  end

  def index
    @users = User.all
    @user = User.find_by(params[:id])
    @current_user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @books = @user.books.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
  unless @user == current_user
     redirect_to user_path(current_user)
  end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
 <% if @book.errors.any? %>
  <%= @book.errors.count %> error occurred.
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2 class="pt-2">Editing Book</h2>
  <%= form_with model: @book do |f| %>
    <p>Title</p>
    <%= f.text_field :title, class: 'px-2 py-1 btn-block'%>
    <br>
    <br>
    <p>Opinion</p>
    <%= f.text_area :body, class: 'px-2 py-1 btn-block' %>
    <br>
    <br>
    <%= f.submit 'Update Book', class: 'btn btn-success btn-sm' %>
  <% end %>
  <br>

  <%= link_to "Show", book_path(@book.id) %>
  <span> | </span>
  <%= link_to "Back", '/books' %>
</div>

<p class="text-center"><br>
  <br>
  CopyRight Infratop.inc</p>

app/views/books/index.html.erb
 <% if @book.errors.any? %>
  <%= @book.errors.count %> error occurred.
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <% if current_user.profile_image.attached? %>
        <%= image_tag current_user.profile_image, size: "100x100", class: 'border-bottom' %>
      <% else %>
        <%= image_tag 'default-image.jpg', size: "100x100", class: 'border-bottom' %>
      <% end %>
      <div class="d-flex">
        <div>
          <p class="border-bottom border-top py-2 font-weight-bold">name</p>
          <p class="py-2 font-weight-bold">introduction</p>
        </div>
        <div class="w-100">
          <p class="text-right border-bottom border-top py-2 pr-4 font-weight-bold"><%= current_user.name %></p>
          <p class="text-right py-2 pr-4 text-right font-weight-bold"><%= current_user.introduction %></p>
        </div>
      </div>

      <%= link_to "/users/#{current_user.id}/edit", class: 'btn btn-light btn-outline-dark btn-block' do %>
        <i class="fas fa-user-cog"></i>
      <% end %>

      <h2>New book</h2>
      <%= form_with model: @book do |f| %>
        <p>Title</p>
        <%= f.text_field :title, class: 'w-100' %>

        <p>Opinion</p>
        <%= f.text_area :body, class: 'w-100' %>

        <%= f.submit 'Create Book', class: 'btn btn-success btn-sm' %>

      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table>
        <thead class="w-100 border-top border-bottom">
          <tr>
            <th></th>
            <th class="py-2">Title</th>
            <th class="py-2">Opinion</th>
          </tr>
        </thead>

        <tbody>
           <% @books.each do |book| %>
            <tr class="border-bottom">
              <td class="py-2 px-2">
                <% if book.user.profile_image.attached? %>
                  <%= link_to image_tag(book.user.profile_image, size: "80x80"), user_path(book.user) %>
                <% else %>
                  <%= link_to image_tag("default-image.jpg", size: "80x80"), user_path(book.user) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %>
                </td>
              <td><%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
  </div>
</div>

<p class="text-center"><br>
    <br>
    CopyRight Infratop.inc
</p>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with model: @book do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>

    <h4>本文</h4>
    <%= f.text_area :body %>

    <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <% if @book.user.profile_image.attached? %>
        <%= image_tag @book.user.profile_image, size: "100x100" %>
      <% else %>
        <%= image_tag 'default-image.jpg', size: "100x100" %>
      <% end %>
      <div class="d-flex">
        <div>
          <p class="border-bottom border-top py-2 font-weight-bold">name</p>
          <p class="py-2 font-weight-bold">introduction</p>
        </div>
        <div class="w-100">
          <p class="text-right border-bottom border-top py-2 pr-4 font-weight-bold"><%= @user.name %></p>
          <p class="text-right py-2 pr-4 text-right font-weight-bold"><%= @user.introduction %></p>
        </div>
      </div>

      <%= link_to edit_user_path(@user.id), class: 'btn btn-light btn-outline-dark btn-block' do %>
        <i class="fas fa-user-cog"></i>
      <% end %>

      <h2>New book</h2>
        <%= form_with model: @new do |f| %>
          <p>Title</p>
          <%= f.text_field :title, class: 'w-100' %>

          <p>Opinion</p>
          <%= f.text_area :body, class: 'w-100' %>

          <%= f.submit 'Create Book', class: 'btn btn-success btn-sm' %>
        <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2 class="pt-2">Book detail</h2>
      <div class="d-flex">
        <div class="w- 100border-top py-2 px-2">
          <% if @book.user.profile_image.attached? %>
            <%= link_to image_tag(@book.user.profile_image, size: "100x100"), user_path(@user.id) %>
          <% else %>
            <%= link_to image_tag("default-image.jpg", size: "100x100"), user_path(@user.id) %>
          <% end %>
          <br>
          <%= link_to @book.user.name, user_path(@user.id) %>
        </div>
        <div class="border-top py-2 pl-5">
          <%= link_to @book.title, book_path(@book.id) %>
        </div>
        <div class="border-top py-2 px-5">
          <%= @book.body %>
        </div>

        <% if @book.user_id == current_user.id %>
        <div class="border-top py-2 px-5">
            <%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-success btn-sm' %>
        </div>
        <div class="border-top py-2 px-5">
            <%= link_to "Destroy", book_path(@book.id), class: 'btn btn-danger btn-sm', method: :delete, "data-confirm" => "削除しますか？" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<p class="text-center"><br>
    <br>
    CopyRight Infratop.inc
</p>

app/views/homes/about.html.erb
<div class="top-text"><h1>welcome to <span class="font-big"><i class="fas fa-book"></i>Bookers !</span></h1>

<p class="text-center"><br>
    <br>
    CopyRight Infratop.inc
</p>

app/views/homes/top.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>welcome to <span class=""><i class="fa-solid fa-book"></i>Bookers !!</span></h1>
  <p class="">
    In <span class=""><i class="fas fa-book"></i>Bookers,</span><br>
    <br>
    you can share and exchange your opinions , inpressions , and emotions<br>
    <br>
    about various books!
  </p>
</div>

<div class="w-25 mx-auto">
  <%= link_to "Log in", new_user_session_path, class: 'btn btn-primary btn-sm btn-block' %>
  <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block' %>
  <p class="text-center"><br>
  <br>
  CopyRight Infratop.inc</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/4b6668ffc2.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark px-5">
          <a href="#" class="navbar-brand pl-5 ">Bookers</a>
          <div class="collapse navbar-collapse justify-content-end" id="nav-menu">
            <div class="navbar-nav">
              <%= link_to user_path(current_user), class: "nav-item nav-link active" do %>
                <i class="fas fa-home pr-1"></i>Home
              <% end %>

              <%= link_to users_path, class: "nav-item nav-link active" do %>
                <i class="fas fa-users pr-1"></i>Users
              <% end %>

              <%= link_to books_path, class: "nav-item nav-link active" do %>
                <i class="fas fa-book-open pr-1"></i>Books
              <% end %>

              <%= link_to destroy_user_session_path, method: :delete, class: "nav-item nav-link active" do %>
                <i class="fas fa-sign-out-alt pr-1"></i> Log out
              <% end %>
            </div>
          </div>
        </nav>
      <% else %>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark px-5">
          <a href="#" class="navbar-brand pl-5 ">Bookers</a>
          <div class="collapse navbar-collapse justify-content-end" id="nav-menu">
            <div class="navbar-nav">
              <%= link_to root_path, class: "nav-item nav-link active" do %>
                <i class="fas fa-home pr-1"></i>Home
              <% end %>

              <%= link_to about_path, class: "nav-item nav-link active" do %>
                <i class="fas fa-link pr-1"></i>About
              <% end %>

              <%= link_to new_user_registration_path, class: "nav-item nav-link active" do %>
                <i class="fas fa-user-plus pr-1"></i> Sign up
              <% end %>

              <%= link_to user_session_path, class: "nav-item nav-link active" do %>
                <i class="fas fa-sign-in-alt pr-1"></i> Log in
              <% end %>
            </div>
          </div>
        </nav>
      <% end %>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
 <% if @user.errors.any? %>
  <%= @user.errors.count %> error occurred.
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2 class="pt-2">User info</h2>
    <%= form_with(model: @user, local: true) do |f| %>
      <p>Name</p>
      <%= f.text_field :name, class: 'py-1 px-2 btn-block' %>
      <br>
      <br>
      <label for="inputImage">Image</label>
      <br>
      <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
      <br>
      <br>
      <p>Intoroducrion</p>
      <%= f.text_area :introduction, class: 'py-1 px-2 btn-block' %>
      <br>
      <%= f.submit "Update User", class: 'btn btn-secondary btn-sm' %>
    <% end %>
    <p class="text-center"><br>
    <br>
    CopyRight Infratop.inc
    </p>
  </div>

app/views/users/index.html.erb
 <% if @current_user.errors.any? %>
  <%= @current_user.errors.count %> error occurred.
  <ul>
    <% @current_user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <% if @current_user.profile_image.attached? %>
        <%= image_tag @current_user.profile_image, size: "100x100" %>
      <% else %>
        <%= image_tag 'default-image.jpg', size: "100x100" %>
      <% end %>
      <div class="d-flex">
        <div>
          <p class="border-bottom border-top py-2 font-weight-bold">name</p>
          <p class="py-2 font-weight-bold">introduction</p>
        </div>
        <div class="w-100">
          <p class="text-right border-bottom border-top py-2 pr-4 font-weight-bold"><%= @current_user.name %></p>
          <p class="text-right py-2 pr-4 text-right font-weight-bold"><%= @current_user.introduction %></p>
        </div>
      </div>

      <%= link_to "/users/#{@current_user.id}/edit", class: 'btn btn-light btn-outline-dark btn-block' do %>
        <i class="fas fa-user-cog"></i>
      <% end %>

      <h2>New book</h2>
      <%= form_with model: @book do |f| %>
        <p>Title</p>
        <%= f.text_field :title, class: 'w-100' %>

        <p>Opinion</p>
        <%= f.text_area :body, class: 'w-100' %>

        <%= f.submit 'Create Book', class: 'btn btn-success btn-sm' %>

      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table>
        <thead class="w-100 border-top border-bottom ">
          <tr>
            <th class="py-2 pl-2 pr-5 col-2">image</th>
            <th class="py-2 px-5 col-4">name</th>
            <th></th>
          </tr>
        </thead>

        <tbody class="col-8">
          <% @users.each do |user| %>
            <tr class="border-bottom">
              <td class="col-2 py-2 pl-2 pr-5">
                <% if user.profile_image.attached? %>
                  <%= link_to image_tag(user.profile_image, size: "80x80"), "/users/#{user.id}" %>
                <% else %>
                  <%= link_to image_tag("default-image.jpg", size: "80x80"), "/users/#{user.id}" %>
                <% end %>
              </td>
              <td class="col-4 py-2 px-5"><%= user.name %>
              </td>
              <td class="col-2 py-2 px-5"><%= link_to "Show", "/users/#{user.id}" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<p class="text-center"><br>
    <br>
    CopyRight Infratop.inc
</p>

app/views/users/show.html.erb
 <% if @user.errors.any? %>
  <%= @user.errors.count %> error occurred.
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <% if @user.profile_image.attached? %>
        <%= image_tag @user.profile_image, size: "100x100" %>
      <% else %>
        <%= image_tag 'default-image.jpg', size: "100x100" %>
      <% end %>
      <div class="d-flex">
        <div>
          <p class="border-bottom border-top py-2 font-weight-bold">name</p>
          <p class="py-2 font-weight-bold">introduction</p>
        </div>
        <div class="w-100">
          <p class="text-right border-bottom border-top py-2 pr-4 font-weight-bold"><%= @user.name %></p>
          <p class="text-right py-2 pr-4 text-right font-weight-bold"><%= @user.introduction %></p>
        </div>
      </div>

      <%= link_to "/users/#{@user.id}/edit", class: 'btn btn-light btn-outline-dark btn-block' do %>
        <i class="fas fa-user-cog"></i>
      <% end %>

      <h2>New book</h2>
      <%= form_with model: @book do |f| %>
        <p>Title</p>
        <%= f.text_field :title, class: 'w-100' %>

        <p>Opinion</p>
        <%= f.text_area :body, class: 'w-100' %>

        <%= f.submit 'Create Book', class: 'btn btn-success btn-sm' %>

      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2 class="pt-2">Books</h2>
      <table>
        <thead class="w-100 border-top border-bottom">
          <tr>
            <th class="py-2 px-5 col-2"></th>
            <th class="py-2 px-5 col-4">Title</th>
            <th class="py-2 px-5 col-4">Opinion</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td class="border-top py-2 pl-2">
                <% if @user.profile_image.attached? %>
                  <%= link_to image_tag(@user.profile_image, size: "80x80"), user_path(@user.id) %>
                <% else %>
                  <%= link_to image_tag('default-image.jpg', size: "80x80"), user_path(@user.id) %>
                <% end %>
              </td>
                <td class="border-top py-2 px-5"><%= link_to book.title, "/books/#{book.id}" %>
                  </td>
                <td class="border-top py-2 px-5"><%= book.body %>
                </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<p class="text-center"><br>
    <br>
    CopyRight Infratop.inc
</p>